name: Auto Deploy to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Sync Repository Files
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Latest Code
        uses: actions/checkout@v4

      - name: Deploy to InfinityFree htdocs
        run: |
          sudo apt-get update && sudo apt-get install -y lftp
          lftp -c "
            set ftp:ssl-allow no;
            set net:timeout 15;
            set net:max-retries 3;
            set ftp:use-site-chmod no;
            set mirror:set-permissions no;
            open -u if0_42655486,GDGCLL123 ftpupload.net;
            mirror --reverse --no-perms --verbose \
              --exclude .git/ \
              --exclude .github/ \
              --exclude README.md \
              ./ htdocs/
          "
